# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb34e6c982a694b30f31b008ced73198"
name = "Pagetest"
handle = "pagetest-ai"
application_url = "https://pagetest-shopify-app-remix.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,write_script_tags,read_products"

[auth]
redirect_urls = [
  "https://pagetest-shopify-app-remix.vercel.app/auth/callback",
  "https://pagetest-shopify-app-remix.vercel.app/auth/shopify/callback",
  "https://pagetest-shopify-app-remix.vercel.app/api/auth/callback"
]

[pos]
embedded = false
