# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb34e6c982a694b30f31b008ced73198"
name = "demo-app-2"
handle = "demo-app-1384"
application_url = "https://testing-map-totals-between.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://testing-map-totals-between.trycloudflare.com/auth/callback",
  "https://testing-map-totals-between.trycloudflare.com/auth/shopify/callback",
  "https://testing-map-totals-between.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
